name: 'Terraform Plan'

on: [push, pull_request]
defaults:
      run:
        shell: bash

jobs:
  opa-validate:
    name: 'OPA Validation'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-west-2'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1
        
      - name: 'Terraform Init'
        run: terraform init
      

      - name: 'Terraform Plan'
        run: terraform plan -out=output
          
          
      - name: 'Terraform plan binary to json'
        run: |
         terraform show -json output > plan.json
      - name: 'Install OPA'
        run: |
         curl -L -o opa https://github.com/open-policy-agent/opa/releases/download/v0.32.0/opa_linux_amd64
         chmod 755 ./opa
         ls
         ./opa eval --format pretty --data *.rego  'data.terraform' 
         ./opa eval --format pretty --data *.rego  --input test.json  'data.terraform' 
         ./opa eval --format pretty --data *.rego --input test.json 'data.terraform.deny' > test.txt
         cat test.txt
         
      - name: 'output  of opa'
        run: |
          cat plan.json
          pwd
          ls
          cat plan.json | head -2 | tail -1 > valid.json
          ./opa eval --format pretty --data *.rego --input valid.json data.terraform
      - name: "Upload Report"
        uses: actions/upload-artifact@v1
        with:
          name: plan
          path: plan.json
  
  
  
#   AWS-Deploy:
#     name: 'Terraform Deploy to AWS'
#     runs-on: ubuntu-latest
#     env:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_REGION: 'us-west-2'
#     steps:
#       - name: 'Checkout'
#         uses: actions/checkout@v2

#       - name: 'Terraform Setup'
#         uses: hashicorp/setup-terraform@v1
        
#       - name: 'Terraform Init'
#         run: |
#          terraform init
#          terraform apply
