name: 'Terraform Plan'

on: [push, pull_request]
defaults:
      run:
        shell: bash

jobs:
  opa-validate:
    name: 'Terraform'
    runs-on: macos-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-west-2'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1
        
      - name: 'Terraform Init'
        run: terraform init
      
      - name: 'Terraform Format'
        run: terraform fmt -check

      - name: 'Terraform Plan'
        run: terraform plan -out=output
        
      - name: 'Terraform plan binary to json'
        run: |
         terraform show -json output > plan.json
         cat plan.json
      - name: 'current path'
        run: pwd
      - name: 'list files'
        run: ls 
#       - name: 'opa Test'
#         uses: ibiqlik/conftest-action-docker@master
#         with:
#           path: "plan.json"
#           namespace: "terraform"
#           policy: "policy.rego"

      - name: 'Install OPA'
        run: |
         curl -L -o opa https://openpolicyagent.org/downloads/v0.32.0/opa_darwin_amd64
         chmod 755 ./opa
         ls
         ./opa eval --format pretty --data policy.rego --input './plan.json' 'data.terraform.deny' > test.txt
         cat test.txt
         
      - name: 'output  of opa'
        run: ./opa eval --format pretty --data policy.rego --input plan.json data.terraform

