name: 'Terraform Plan'

on: [push, pull_request]
defaults:
      run:
        shell: bash

jobs:
  opa-validate:
    name: 'OPA Validation'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-west-2'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1
        
      - name: 'Terraform Init'
        run: terraform init
      

      - name: 'Terraform Plan'
        run: terraform plan -out=output
          
          
      - name: 'Terraform plan binary to json'
        run: |
         terraform show -json output > plan.json
      - name: 'Install OPA'
        run: |
         curl -L -o opa https://github.com/open-policy-agent/opa/releases/download/v0.32.0/opa_linux_amd64
         chmod 755 ./opa

         
      - name: 'output  of opa'
        run: |
          ./opa eval --format pretty --data *.rego --input plan.json data.terraform.deny > now.txt
          cat plan.json | head -2 | tail -1 > valid.json
          ./opa eval --format pretty --data *.rego --input valid.json data.terraform
          ./opa eval --format pretty --data *.rego --input valid.json data.terraform.deny > test.txt
          cat test.txt
      - name: conditional command
        run: |
          output=$(awk 'BEGIN{c=0} //{c++} END{print c}' RS="[[:space:]]" test.txt)
          echo $output
          if: {{ $output <= 2 }}
            echo $output
          if: {{ $output > 2 }}
            echo $output

